// -*- C++ -*-
// This is a header file generated with the command:
// makeCMS3ClassFiles("/nfs-7/userdata/phchang/WWW_babies/FR2017_v3.0.13/link/WJetsToLNu_TuneCP5_13TeV-madgraphMLM_ext1_output_1.root", "t", "frtree", "tas", "fr")

#ifndef frtree_H
#define frtree_H

#include "Math/LorentzVector.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector> 
#include <unistd.h> 
typedef ROOT::Math::LorentzVector< ROOT::Math::PxPyPzE4D<float> > LorentzVector;

using namespace std; 
class frtree {
 private: 
 protected: 
  unsigned int index;
  int      run_;
  TBranch *run_branch;
  bool     run_isLoaded;
  int      lumi_;
  TBranch *lumi_branch;
  bool     lumi_isLoaded;
  unsigned long long evt_;
  TBranch *evt_branch;
  bool     evt_isLoaded;
  int      isData_;
  TBranch *isData_branch;
  bool     isData_isLoaded;
  float    evt_scale1fb_;
  TBranch *evt_scale1fb_branch;
  bool     evt_scale1fb_isLoaded;
  float    xsec_br_;
  TBranch *xsec_br_branch;
  bool     xsec_br_isLoaded;
  int      evt_passgoodrunlist_;
  TBranch *evt_passgoodrunlist_branch;
  bool     evt_passgoodrunlist_isLoaded;
  TString *CMS4path_;
  TBranch *CMS4path_branch;
  bool     CMS4path_isLoaded;
  int      CMS4index_;
  TBranch *CMS4index_branch;
  bool     CMS4index_isLoaded;
  float    weight_fr_r1_f1_;
  TBranch *weight_fr_r1_f1_branch;
  bool     weight_fr_r1_f1_isLoaded;
  float    weight_fr_r1_f2_;
  TBranch *weight_fr_r1_f2_branch;
  bool     weight_fr_r1_f2_isLoaded;
  float    weight_fr_r1_f0p5_;
  TBranch *weight_fr_r1_f0p5_branch;
  bool     weight_fr_r1_f0p5_isLoaded;
  float    weight_fr_r2_f1_;
  TBranch *weight_fr_r2_f1_branch;
  bool     weight_fr_r2_f1_isLoaded;
  float    weight_fr_r2_f2_;
  TBranch *weight_fr_r2_f2_branch;
  bool     weight_fr_r2_f2_isLoaded;
  float    weight_fr_r2_f0p5_;
  TBranch *weight_fr_r2_f0p5_branch;
  bool     weight_fr_r2_f0p5_isLoaded;
  float    weight_fr_r0p5_f1_;
  TBranch *weight_fr_r0p5_f1_branch;
  bool     weight_fr_r0p5_f1_isLoaded;
  float    weight_fr_r0p5_f2_;
  TBranch *weight_fr_r0p5_f2_branch;
  bool     weight_fr_r0p5_f2_isLoaded;
  float    weight_fr_r0p5_f0p5_;
  TBranch *weight_fr_r0p5_f0p5_branch;
  bool     weight_fr_r0p5_f0p5_isLoaded;
  float    weight_pdf_up_;
  TBranch *weight_pdf_up_branch;
  bool     weight_pdf_up_isLoaded;
  float    weight_pdf_down_;
  TBranch *weight_pdf_down_branch;
  bool     weight_pdf_down_isLoaded;
  float    weight_alphas_down_;
  TBranch *weight_alphas_down_branch;
  bool     weight_alphas_down_isLoaded;
  float    weight_alphas_up_;
  TBranch *weight_alphas_up_branch;
  bool     weight_alphas_up_isLoaded;
  float    weight_isr_;
  TBranch *weight_isr_branch;
  bool     weight_isr_isLoaded;
  float    weight_isr_up_;
  TBranch *weight_isr_up_branch;
  bool     weight_isr_up_isLoaded;
  float    weight_isr_down_;
  TBranch *weight_isr_down_branch;
  bool     weight_isr_down_isLoaded;
  int      HLT_DoubleMu_;
  TBranch *HLT_DoubleMu_branch;
  bool     HLT_DoubleMu_isLoaded;
  int      HLT_DoubleEl_;
  TBranch *HLT_DoubleEl_branch;
  bool     HLT_DoubleEl_isLoaded;
  int      HLT_DoubleEl_DZ_;
  TBranch *HLT_DoubleEl_DZ_branch;
  bool     HLT_DoubleEl_DZ_isLoaded;
  int      HLT_DoubleEl_DZ_2_;
  TBranch *HLT_DoubleEl_DZ_2_branch;
  bool     HLT_DoubleEl_DZ_2_isLoaded;
  int      HLT_MuEG_;
  TBranch *HLT_MuEG_branch;
  bool     HLT_MuEG_isLoaded;
  int      HLT_SingleEl8_;
  TBranch *HLT_SingleEl8_branch;
  bool     HLT_SingleEl8_isLoaded;
  int      HLT_SingleEl17_;
  TBranch *HLT_SingleEl17_branch;
  bool     HLT_SingleEl17_isLoaded;
  int      HLT_SingleIsoEl8_;
  TBranch *HLT_SingleIsoEl8_branch;
  bool     HLT_SingleIsoEl8_isLoaded;
  int      HLT_SingleIsoEl17_;
  TBranch *HLT_SingleIsoEl17_branch;
  bool     HLT_SingleIsoEl17_isLoaded;
  int      HLT_SingleIsoEl23_;
  TBranch *HLT_SingleIsoEl23_branch;
  bool     HLT_SingleIsoEl23_isLoaded;
  int      HLT_SingleIsoMu8_;
  TBranch *HLT_SingleIsoMu8_branch;
  bool     HLT_SingleIsoMu8_isLoaded;
  int      HLT_SingleIsoMu17_;
  TBranch *HLT_SingleIsoMu17_branch;
  bool     HLT_SingleIsoMu17_isLoaded;
  int      HLT_PFMET140_PFMHT140_IDTight_;
  TBranch *HLT_PFMET140_PFMHT140_IDTight_branch;
  bool     HLT_PFMET140_PFMHT140_IDTight_isLoaded;
  int      mc_HLT_DoubleMu_;
  TBranch *mc_HLT_DoubleMu_branch;
  bool     mc_HLT_DoubleMu_isLoaded;
  int      mc_HLT_DoubleEl_;
  TBranch *mc_HLT_DoubleEl_branch;
  bool     mc_HLT_DoubleEl_isLoaded;
  int      mc_HLT_DoubleEl_DZ_;
  TBranch *mc_HLT_DoubleEl_DZ_branch;
  bool     mc_HLT_DoubleEl_DZ_isLoaded;
  int      mc_HLT_DoubleEl_DZ_2_;
  TBranch *mc_HLT_DoubleEl_DZ_2_branch;
  bool     mc_HLT_DoubleEl_DZ_2_isLoaded;
  int      mc_HLT_MuEG_;
  TBranch *mc_HLT_MuEG_branch;
  bool     mc_HLT_MuEG_isLoaded;
  int      mc_HLT_SingleEl8_;
  TBranch *mc_HLT_SingleEl8_branch;
  bool     mc_HLT_SingleEl8_isLoaded;
  int      mc_HLT_SingleEl17_;
  TBranch *mc_HLT_SingleEl17_branch;
  bool     mc_HLT_SingleEl17_isLoaded;
  int      mc_HLT_SingleIsoEl8_;
  TBranch *mc_HLT_SingleIsoEl8_branch;
  bool     mc_HLT_SingleIsoEl8_isLoaded;
  int      mc_HLT_SingleIsoEl17_;
  TBranch *mc_HLT_SingleIsoEl17_branch;
  bool     mc_HLT_SingleIsoEl17_isLoaded;
  int      mc_HLT_SingleIsoEl23_;
  TBranch *mc_HLT_SingleIsoEl23_branch;
  bool     mc_HLT_SingleIsoEl23_isLoaded;
  int      mc_HLT_SingleIsoMu8_;
  TBranch *mc_HLT_SingleIsoMu8_branch;
  bool     mc_HLT_SingleIsoMu8_isLoaded;
  int      mc_HLT_SingleIsoMu17_;
  TBranch *mc_HLT_SingleIsoMu17_branch;
  bool     mc_HLT_SingleIsoMu17_isLoaded;
  int      mc_HLT_PFMET140_PFMHT140_IDTight_;
  TBranch *mc_HLT_PFMET140_PFMHT140_IDTight_branch;
  bool     mc_HLT_PFMET140_PFMHT140_IDTight_isLoaded;
  int      pass_duplicate_ee_em_mm_;
  TBranch *pass_duplicate_ee_em_mm_branch;
  bool     pass_duplicate_ee_em_mm_isLoaded;
  int      pass_duplicate_mm_em_ee_;
  TBranch *pass_duplicate_mm_em_ee_branch;
  bool     pass_duplicate_mm_em_ee_isLoaded;
  int      is2016_;
  TBranch *is2016_branch;
  bool     is2016_isLoaded;
  int      is2017_;
  TBranch *is2017_branch;
  bool     is2017_isLoaded;
  int      HLT_MuEG_2016_;
  TBranch *HLT_MuEG_2016_branch;
  bool     HLT_MuEG_2016_isLoaded;
  int      mc_HLT_MuEG_2016_;
  TBranch *mc_HLT_MuEG_2016_branch;
  bool     mc_HLT_MuEG_2016_isLoaded;
  int      pass_duplicate_ee_em2016_mm_;
  TBranch *pass_duplicate_ee_em2016_mm_branch;
  bool     pass_duplicate_ee_em2016_mm_isLoaded;
  int      pass_duplicate_mm_em2016_ee_;
  TBranch *pass_duplicate_mm_em2016_ee_branch;
  bool     pass_duplicate_mm_em2016_ee_isLoaded;
  int      passTrigger_;
  TBranch *passTrigger_branch;
  bool     passTrigger_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *lep_p4_;
  TBranch *lep_p4_branch;
  bool     lep_p4_isLoaded;
  vector<float> *lep_pt_;
  TBranch *lep_pt_branch;
  bool     lep_pt_isLoaded;
  vector<float> *lep_eta_;
  TBranch *lep_eta_branch;
  bool     lep_eta_isLoaded;
  vector<float> *lep_phi_;
  TBranch *lep_phi_branch;
  bool     lep_phi_isLoaded;
  vector<float> *lep_coneCorrPt_;
  TBranch *lep_coneCorrPt_branch;
  bool     lep_coneCorrPt_isLoaded;
  vector<float> *lep_ip3d_;
  TBranch *lep_ip3d_branch;
  bool     lep_ip3d_isLoaded;
  vector<float> *lep_ip3derr_;
  TBranch *lep_ip3derr_branch;
  bool     lep_ip3derr_isLoaded;
  vector<int> *lep_isTriggerSafe_v1_;
  TBranch *lep_isTriggerSafe_v1_branch;
  bool     lep_isTriggerSafe_v1_isLoaded;
  vector<int> *lep_lostHits_;
  TBranch *lep_lostHits_branch;
  bool     lep_lostHits_isLoaded;
  vector<int> *lep_convVeto_;
  TBranch *lep_convVeto_branch;
  bool     lep_convVeto_isLoaded;
  vector<int> *lep_motherIdSS_;
  TBranch *lep_motherIdSS_branch;
  bool     lep_motherIdSS_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_3l_fo_;
  TBranch *lep_pass_VVV_cutbased_3l_fo_branch;
  bool     lep_pass_VVV_cutbased_3l_fo_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_3l_tight_;
  TBranch *lep_pass_VVV_cutbased_3l_tight_branch;
  bool     lep_pass_VVV_cutbased_3l_tight_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_fo_;
  TBranch *lep_pass_VVV_cutbased_fo_branch;
  bool     lep_pass_VVV_cutbased_fo_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_tight_;
  TBranch *lep_pass_VVV_cutbased_tight_branch;
  bool     lep_pass_VVV_cutbased_tight_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_veto_;
  TBranch *lep_pass_VVV_cutbased_veto_branch;
  bool     lep_pass_VVV_cutbased_veto_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_fo_noiso_;
  TBranch *lep_pass_VVV_cutbased_fo_noiso_branch;
  bool     lep_pass_VVV_cutbased_fo_noiso_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_tight_noiso_;
  TBranch *lep_pass_VVV_cutbased_tight_noiso_branch;
  bool     lep_pass_VVV_cutbased_tight_noiso_isLoaded;
  vector<int> *lep_pass_VVV_cutbased_veto_noiso_;
  TBranch *lep_pass_VVV_cutbased_veto_noiso_branch;
  bool     lep_pass_VVV_cutbased_veto_noiso_isLoaded;
  vector<int> *lep_pass_POG_veto_;
  TBranch *lep_pass_POG_veto_branch;
  bool     lep_pass_POG_veto_isLoaded;
  vector<int> *lep_pass_POG_loose_;
  TBranch *lep_pass_POG_loose_branch;
  bool     lep_pass_POG_loose_isLoaded;
  vector<int> *lep_pass_POG_medium_;
  TBranch *lep_pass_POG_medium_branch;
  bool     lep_pass_POG_medium_isLoaded;
  vector<int> *lep_pass_POG_tight_;
  TBranch *lep_pass_POG_tight_branch;
  bool     lep_pass_POG_tight_isLoaded;
  vector<int> *lep_pdgId_;
  TBranch *lep_pdgId_branch;
  bool     lep_pdgId_isLoaded;
  vector<float> *lep_dxy_;
  TBranch *lep_dxy_branch;
  bool     lep_dxy_isLoaded;
  vector<float> *lep_dz_;
  TBranch *lep_dz_branch;
  bool     lep_dz_isLoaded;
  vector<float> *lep_pterr_;
  TBranch *lep_pterr_branch;
  bool     lep_pterr_isLoaded;
  vector<float> *lep_relIso04DB_;
  TBranch *lep_relIso04DB_branch;
  bool     lep_relIso04DB_isLoaded;
  vector<float> *lep_relIso03EA_;
  TBranch *lep_relIso03EA_branch;
  bool     lep_relIso03EA_isLoaded;
  vector<float> *lep_relIso03EALep_;
  TBranch *lep_relIso03EALep_branch;
  bool     lep_relIso03EALep_isLoaded;
  vector<float> *lep_relIso03EAv2_;
  TBranch *lep_relIso03EAv2_branch;
  bool     lep_relIso03EAv2_isLoaded;
  vector<float> *lep_relIso04EAv2_;
  TBranch *lep_relIso04EAv2_branch;
  bool     lep_relIso04EAv2_isLoaded;
  vector<float> *lep_relIso03EAv2Lep_;
  TBranch *lep_relIso03EAv2Lep_branch;
  bool     lep_relIso03EAv2Lep_isLoaded;
  vector<int> *lep_tightCharge_;
  TBranch *lep_tightCharge_branch;
  bool     lep_tightCharge_isLoaded;
  vector<float> *lep_trk_pt_;
  TBranch *lep_trk_pt_branch;
  bool     lep_trk_pt_isLoaded;
  vector<int> *lep_charge_;
  TBranch *lep_charge_branch;
  bool     lep_charge_isLoaded;
  vector<float> *lep_etaSC_;
  TBranch *lep_etaSC_branch;
  bool     lep_etaSC_isLoaded;
  vector<float> *lep_MVA_;
  TBranch *lep_MVA_branch;
  bool     lep_MVA_isLoaded;
  vector<int> *lep_isMediumPOG_;
  TBranch *lep_isMediumPOG_branch;
  bool     lep_isMediumPOG_isLoaded;
  vector<int> *lep_isTightPOG_;
  TBranch *lep_isTightPOG_branch;
  bool     lep_isTightPOG_isLoaded;
  vector<int> *lep_isFromW_;
  TBranch *lep_isFromW_branch;
  bool     lep_isFromW_isLoaded;
  vector<int> *lep_isFromZ_;
  TBranch *lep_isFromZ_branch;
  bool     lep_isFromZ_isLoaded;
  vector<int> *lep_isFromB_;
  TBranch *lep_isFromB_branch;
  bool     lep_isFromB_isLoaded;
  vector<int> *lep_isFromC_;
  TBranch *lep_isFromC_branch;
  bool     lep_isFromC_isLoaded;
  vector<int> *lep_isFromL_;
  TBranch *lep_isFromL_branch;
  bool     lep_isFromL_isLoaded;
  vector<int> *lep_isFromLF_;
  TBranch *lep_isFromLF_branch;
  bool     lep_isFromLF_isLoaded;
  vector<int> *lep_genPart_index_;
  TBranch *lep_genPart_index_branch;
  bool     lep_genPart_index_isLoaded;
  vector<float> *lep_r9_;
  TBranch *lep_r9_branch;
  bool     lep_r9_isLoaded;
  vector<int> *lep_nlayers_;
  TBranch *lep_nlayers_branch;
  bool     lep_nlayers_isLoaded;
  float    el_pt_;
  TBranch *el_pt_branch;
  bool     el_pt_isLoaded;
  float    el_eta_;
  TBranch *el_eta_branch;
  bool     el_eta_isLoaded;
  float    el_phi_;
  TBranch *el_phi_branch;
  bool     el_phi_isLoaded;
  float    el_relIso03EA_;
  TBranch *el_relIso03EA_branch;
  bool     el_relIso03EA_isLoaded;
  float    el_relIso03EALep_;
  TBranch *el_relIso03EALep_branch;
  bool     el_relIso03EALep_isLoaded;
  float    el_ip3d_;
  TBranch *el_ip3d_branch;
  bool     el_ip3d_isLoaded;
  float    mu_pt_;
  TBranch *mu_pt_branch;
  bool     mu_pt_isLoaded;
  float    mu_eta_;
  TBranch *mu_eta_branch;
  bool     mu_eta_isLoaded;
  float    mu_phi_;
  TBranch *mu_phi_branch;
  bool     mu_phi_isLoaded;
  float    mu_relIso04DB_;
  TBranch *mu_relIso04DB_branch;
  bool     mu_relIso04DB_isLoaded;
  float    mu_relIso03EA_;
  TBranch *mu_relIso03EA_branch;
  bool     mu_relIso03EA_isLoaded;
  float    mu_relIso03EALep_;
  TBranch *mu_relIso03EALep_branch;
  bool     mu_relIso03EALep_isLoaded;
  float    mu_ip3d_;
  TBranch *mu_ip3d_branch;
  bool     mu_ip3d_isLoaded;
  float    lbnt_pt_;
  TBranch *lbnt_pt_branch;
  bool     lbnt_pt_isLoaded;
  float    lbnt_coneCorrPt_;
  TBranch *lbnt_coneCorrPt_branch;
  bool     lbnt_coneCorrPt_isLoaded;
  float    lbnt_abseta_;
  TBranch *lbnt_abseta_branch;
  bool     lbnt_abseta_isLoaded;
  float    lbnt_pdgId_;
  TBranch *lbnt_pdgId_branch;
  bool     lbnt_pdgId_isLoaded;
  float    lbnt_el_pt_;
  TBranch *lbnt_el_pt_branch;
  bool     lbnt_el_pt_isLoaded;
  float    lbnt_el_coneCorrPt_;
  TBranch *lbnt_el_coneCorrPt_branch;
  bool     lbnt_el_coneCorrPt_isLoaded;
  float    lbnt_el_abseta_;
  TBranch *lbnt_el_abseta_branch;
  bool     lbnt_el_abseta_isLoaded;
  float    lbnt_mu_pt_;
  TBranch *lbnt_mu_pt_branch;
  bool     lbnt_mu_pt_isLoaded;
  float    lbnt_mu_coneCorrPt_;
  TBranch *lbnt_mu_coneCorrPt_branch;
  bool     lbnt_mu_coneCorrPt_isLoaded;
  float    lbnt_mu_abseta_;
  TBranch *lbnt_mu_abseta_branch;
  bool     lbnt_mu_abseta_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_p4_;
  TBranch *jets_p4_branch;
  bool     jets_p4_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_up_p4_;
  TBranch *jets_up_p4_branch;
  bool     jets_up_p4_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_dn_p4_;
  TBranch *jets_dn_p4_branch;
  bool     jets_dn_p4_isLoaded;
  vector<float> *jets_csv_;
  TBranch *jets_csv_branch;
  bool     jets_csv_isLoaded;
  vector<float> *jets_up_csv_;
  TBranch *jets_up_csv_branch;
  bool     jets_up_csv_isLoaded;
  vector<float> *jets_dn_csv_;
  TBranch *jets_dn_csv_branch;
  bool     jets_dn_csv_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *ak8jets_p4_;
  TBranch *ak8jets_p4_branch;
  bool     ak8jets_p4_isLoaded;
  vector<float> *ak8jets_softdropMass_;
  TBranch *ak8jets_softdropMass_branch;
  bool     ak8jets_softdropMass_isLoaded;
  vector<float> *ak8jets_prunedMass_;
  TBranch *ak8jets_prunedMass_branch;
  bool     ak8jets_prunedMass_isLoaded;
  vector<float> *ak8jets_trimmedMass_;
  TBranch *ak8jets_trimmedMass_branch;
  bool     ak8jets_trimmedMass_isLoaded;
  vector<float> *ak8jets_mass_;
  TBranch *ak8jets_mass_branch;
  bool     ak8jets_mass_isLoaded;
  vector<float> *ak8jets_nJettinessTau1_;
  TBranch *ak8jets_nJettinessTau1_branch;
  bool     ak8jets_nJettinessTau1_isLoaded;
  vector<float> *ak8jets_nJettinessTau2_;
  TBranch *ak8jets_nJettinessTau2_branch;
  bool     ak8jets_nJettinessTau2_isLoaded;
  vector<float> *ak8jets_softdropPuppiSubjet1_;
  TBranch *ak8jets_softdropPuppiSubjet1_branch;
  bool     ak8jets_softdropPuppiSubjet1_isLoaded;
  vector<float> *ak8jets_softdropPuppiSubjet2_;
  TBranch *ak8jets_softdropPuppiSubjet2_branch;
  bool     ak8jets_softdropPuppiSubjet2_isLoaded;
  vector<float> *ak8jets_puppi_softdropMass_;
  TBranch *ak8jets_puppi_softdropMass_branch;
  bool     ak8jets_puppi_softdropMass_isLoaded;
  vector<float> *ak8jets_puppi_nJettinessTau1_;
  TBranch *ak8jets_puppi_nJettinessTau1_branch;
  bool     ak8jets_puppi_nJettinessTau1_isLoaded;
  vector<float> *ak8jets_puppi_nJettinessTau2_;
  TBranch *ak8jets_puppi_nJettinessTau2_branch;
  bool     ak8jets_puppi_nJettinessTau2_isLoaded;
  vector<float> *ak8jets_puppi_eta_;
  TBranch *ak8jets_puppi_eta_branch;
  bool     ak8jets_puppi_eta_isLoaded;
  vector<float> *ak8jets_puppi_phi_;
  TBranch *ak8jets_puppi_phi_branch;
  bool     ak8jets_puppi_phi_isLoaded;
  vector<float> *ak8jets_puppi_pt_;
  TBranch *ak8jets_puppi_pt_branch;
  bool     ak8jets_puppi_pt_isLoaded;
  vector<float> *ak8jets_puppi_mass_;
  TBranch *ak8jets_puppi_mass_branch;
  bool     ak8jets_puppi_mass_isLoaded;
  float    met_pt_;
  TBranch *met_pt_branch;
  bool     met_pt_isLoaded;
  float    met_phi_;
  TBranch *met_phi_branch;
  bool     met_phi_isLoaded;
  float    met_up_pt_;
  TBranch *met_up_pt_branch;
  bool     met_up_pt_isLoaded;
  float    met_up_phi_;
  TBranch *met_up_phi_branch;
  bool     met_up_phi_isLoaded;
  float    met_dn_pt_;
  TBranch *met_dn_pt_branch;
  bool     met_dn_pt_isLoaded;
  float    met_dn_phi_;
  TBranch *met_dn_phi_branch;
  bool     met_dn_phi_isLoaded;
  float    met_gen_pt_;
  TBranch *met_gen_pt_branch;
  bool     met_gen_pt_isLoaded;
  float    met_gen_phi_;
  TBranch *met_gen_phi_branch;
  bool     met_gen_phi_isLoaded;
  int      firstgoodvertex_;
  TBranch *firstgoodvertex_branch;
  bool     firstgoodvertex_isLoaded;
  int      nTrueInt_;
  TBranch *nTrueInt_branch;
  bool     nTrueInt_isLoaded;
  int      nVert_;
  TBranch *nVert_branch;
  bool     nVert_isLoaded;
  int      nisoTrack_mt2_cleaned_VVV_cutbased_veto_;
  TBranch *nisoTrack_mt2_cleaned_VVV_cutbased_veto_branch;
  bool     nisoTrack_mt2_cleaned_VVV_cutbased_veto_isLoaded;
  float    weight_btagsf_;
  TBranch *weight_btagsf_branch;
  bool     weight_btagsf_isLoaded;
  float    weight_btagsf_heavy_DN_;
  TBranch *weight_btagsf_heavy_DN_branch;
  bool     weight_btagsf_heavy_DN_isLoaded;
  float    weight_btagsf_heavy_UP_;
  TBranch *weight_btagsf_heavy_UP_branch;
  bool     weight_btagsf_heavy_UP_isLoaded;
  float    weight_btagsf_light_DN_;
  TBranch *weight_btagsf_light_DN_branch;
  bool     weight_btagsf_light_DN_isLoaded;
  float    weight_btagsf_light_UP_;
  TBranch *weight_btagsf_light_UP_branch;
  bool     weight_btagsf_light_UP_isLoaded;
  float    gen_ht_;
  TBranch *gen_ht_branch;
  bool     gen_ht_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *genPart_p4_;
  TBranch *genPart_p4_branch;
  bool     genPart_p4_isLoaded;
  vector<int> *genPart_motherId_;
  TBranch *genPart_motherId_branch;
  bool     genPart_motherId_isLoaded;
  vector<int> *genPart_pdgId_;
  TBranch *genPart_pdgId_branch;
  bool     genPart_pdgId_isLoaded;
  vector<int> *genPart_charge_;
  TBranch *genPart_charge_branch;
  bool     genPart_charge_isLoaded;
  vector<int> *genPart_status_;
  TBranch *genPart_status_branch;
  bool     genPart_status_isLoaded;
  int      ngenLep_;
  TBranch *ngenLep_branch;
  bool     ngenLep_isLoaded;
  int      ngenLepFromTau_;
  TBranch *ngenLepFromTau_branch;
  bool     ngenLepFromTau_isLoaded;
  int      Flag_AllEventFilters_;
  TBranch *Flag_AllEventFilters_branch;
  bool     Flag_AllEventFilters_isLoaded;
  int      Flag_EcalDeadCellTriggerPrimitiveFilter_;
  TBranch *Flag_EcalDeadCellTriggerPrimitiveFilter_branch;
  bool     Flag_EcalDeadCellTriggerPrimitiveFilter_isLoaded;
  int      Flag_HBHEIsoNoiseFilter_;
  TBranch *Flag_HBHEIsoNoiseFilter_branch;
  bool     Flag_HBHEIsoNoiseFilter_isLoaded;
  int      Flag_HBHENoiseFilter_;
  TBranch *Flag_HBHENoiseFilter_branch;
  bool     Flag_HBHENoiseFilter_isLoaded;
  int      Flag_badChargedCandidateFilter_;
  TBranch *Flag_badChargedCandidateFilter_branch;
  bool     Flag_badChargedCandidateFilter_isLoaded;
  int      Flag_badMuonFilter_;
  TBranch *Flag_badMuonFilter_branch;
  bool     Flag_badMuonFilter_isLoaded;
  int      Flag_badMuonFilterv2_;
  TBranch *Flag_badMuonFilterv2_branch;
  bool     Flag_badMuonFilterv2_isLoaded;
  int      Flag_badChargedCandidateFilterv2_;
  TBranch *Flag_badChargedCandidateFilterv2_branch;
  bool     Flag_badChargedCandidateFilterv2_isLoaded;
  int      Flag_eeBadScFilter_;
  TBranch *Flag_eeBadScFilter_branch;
  bool     Flag_eeBadScFilter_isLoaded;
  int      Flag_ecalBadCalibFilter_;
  TBranch *Flag_ecalBadCalibFilter_branch;
  bool     Flag_ecalBadCalibFilter_isLoaded;
  int      Flag_globalTightHalo2016_;
  TBranch *Flag_globalTightHalo2016_branch;
  bool     Flag_globalTightHalo2016_isLoaded;
  int      Flag_goodVertices_;
  TBranch *Flag_goodVertices_branch;
  bool     Flag_goodVertices_isLoaded;
  int      Flag_ecalLaserCorrFilter_;
  TBranch *Flag_ecalLaserCorrFilter_branch;
  bool     Flag_ecalLaserCorrFilter_isLoaded;
  int      Flag_hcalLaserEventFilter_;
  TBranch *Flag_hcalLaserEventFilter_branch;
  bool     Flag_hcalLaserEventFilter_isLoaded;
  int      Flag_trackingFailureFilter_;
  TBranch *Flag_trackingFailureFilter_branch;
  bool     Flag_trackingFailureFilter_isLoaded;
  int      Flag_CSCTightHaloFilter_;
  TBranch *Flag_CSCTightHaloFilter_branch;
  bool     Flag_CSCTightHaloFilter_isLoaded;
  int      Flag_CSCTightHalo2015Filter_;
  TBranch *Flag_CSCTightHalo2015Filter_branch;
  bool     Flag_CSCTightHalo2015Filter_isLoaded;
  int      Flag_badMuons_;
  TBranch *Flag_badMuons_branch;
  bool     Flag_badMuons_isLoaded;
  int      Flag_duplicateMuons_;
  TBranch *Flag_duplicateMuons_branch;
  bool     Flag_duplicateMuons_isLoaded;
  int      Flag_noBadMuons_;
  TBranch *Flag_noBadMuons_branch;
  bool     Flag_noBadMuons_isLoaded;
  int      fastsimfilt_;
  TBranch *fastsimfilt_branch;
  bool     fastsimfilt_isLoaded;
  int      nVlep_;
  TBranch *nVlep_branch;
  bool     nVlep_isLoaded;
  int      nTlep_;
  TBranch *nTlep_branch;
  bool     nTlep_isLoaded;
  int      nTlepSS_;
  TBranch *nTlepSS_branch;
  bool     nTlepSS_isLoaded;
  int      nLlep_;
  TBranch *nLlep_branch;
  bool     nLlep_isLoaded;
  int      nSFOS_;
  TBranch *nSFOS_branch;
  bool     nSFOS_isLoaded;
  int      nSFOSinZ_;
  TBranch *nSFOSinZ_branch;
  bool     nSFOSinZ_isLoaded;
  int      nj_;
  TBranch *nj_branch;
  bool     nj_isLoaded;
  int      nj_up_;
  TBranch *nj_up_branch;
  bool     nj_up_isLoaded;
  int      nj_dn_;
  TBranch *nj_dn_branch;
  bool     nj_dn_isLoaded;
  int      nj30_;
  TBranch *nj30_branch;
  bool     nj30_isLoaded;
  int      nj30_up_;
  TBranch *nj30_up_branch;
  bool     nj30_up_isLoaded;
  int      nj30_dn_;
  TBranch *nj30_dn_branch;
  bool     nj30_dn_isLoaded;
  int      nb_;
  TBranch *nb_branch;
  bool     nb_isLoaded;
  int      nb_up_;
  TBranch *nb_up_branch;
  bool     nb_up_isLoaded;
  int      nb_dn_;
  TBranch *nb_dn_branch;
  bool     nb_dn_isLoaded;
  float    Mjj_;
  TBranch *Mjj_branch;
  bool     Mjj_isLoaded;
  float    Mjj_up_;
  TBranch *Mjj_up_branch;
  bool     Mjj_up_isLoaded;
  float    Mjj_dn_;
  TBranch *Mjj_dn_branch;
  bool     Mjj_dn_isLoaded;
  float    DRjj_;
  TBranch *DRjj_branch;
  bool     DRjj_isLoaded;
  float    DRjj_up_;
  TBranch *DRjj_up_branch;
  bool     DRjj_up_isLoaded;
  float    DRjj_dn_;
  TBranch *DRjj_dn_branch;
  bool     DRjj_dn_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_;
  TBranch *jet0_wtag_p4_branch;
  bool     jet0_wtag_p4_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_up_;
  TBranch *jet0_wtag_p4_up_branch;
  bool     jet0_wtag_p4_up_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_dn_;
  TBranch *jet0_wtag_p4_dn_branch;
  bool     jet0_wtag_p4_dn_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_;
  TBranch *jet1_wtag_p4_branch;
  bool     jet1_wtag_p4_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_up_;
  TBranch *jet1_wtag_p4_up_branch;
  bool     jet1_wtag_p4_up_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_dn_;
  TBranch *jet1_wtag_p4_dn_branch;
  bool     jet1_wtag_p4_dn_isLoaded;
  float    MjjDR1_;
  TBranch *MjjDR1_branch;
  bool     MjjDR1_isLoaded;
  float    MjjDR1_up_;
  TBranch *MjjDR1_up_branch;
  bool     MjjDR1_up_isLoaded;
  float    MjjDR1_dn_;
  TBranch *MjjDR1_dn_branch;
  bool     MjjDR1_dn_isLoaded;
  float    DRjjDR1_;
  TBranch *DRjjDR1_branch;
  bool     DRjjDR1_isLoaded;
  float    DRjjDR1_up_;
  TBranch *DRjjDR1_up_branch;
  bool     DRjjDR1_up_isLoaded;
  float    DRjjDR1_dn_;
  TBranch *DRjjDR1_dn_branch;
  bool     DRjjDR1_dn_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_DR1_;
  TBranch *jet0_wtag_p4_DR1_branch;
  bool     jet0_wtag_p4_DR1_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_DR1_up_;
  TBranch *jet0_wtag_p4_DR1_up_branch;
  bool     jet0_wtag_p4_DR1_up_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet0_wtag_p4_DR1_dn_;
  TBranch *jet0_wtag_p4_DR1_dn_branch;
  bool     jet0_wtag_p4_DR1_dn_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_DR1_;
  TBranch *jet1_wtag_p4_DR1_branch;
  bool     jet1_wtag_p4_DR1_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_DR1_up_;
  TBranch *jet1_wtag_p4_DR1_up_branch;
  bool     jet1_wtag_p4_DR1_up_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *jet1_wtag_p4_DR1_dn_;
  TBranch *jet1_wtag_p4_DR1_dn_branch;
  bool     jet1_wtag_p4_DR1_dn_isLoaded;
  float    MjjVBF_;
  TBranch *MjjVBF_branch;
  bool     MjjVBF_isLoaded;
  float    MjjVBF_up_;
  TBranch *MjjVBF_up_branch;
  bool     MjjVBF_up_isLoaded;
  float    MjjVBF_dn_;
  TBranch *MjjVBF_dn_branch;
  bool     MjjVBF_dn_isLoaded;
  float    DetajjVBF_;
  TBranch *DetajjVBF_branch;
  bool     DetajjVBF_isLoaded;
  float    DetajjVBF_up_;
  TBranch *DetajjVBF_up_branch;
  bool     DetajjVBF_up_isLoaded;
  float    DetajjVBF_dn_;
  TBranch *DetajjVBF_dn_branch;
  bool     DetajjVBF_dn_isLoaded;
  float    MjjL_;
  TBranch *MjjL_branch;
  bool     MjjL_isLoaded;
  float    MjjL_up_;
  TBranch *MjjL_up_branch;
  bool     MjjL_up_isLoaded;
  float    MjjL_dn_;
  TBranch *MjjL_dn_branch;
  bool     MjjL_dn_isLoaded;
  float    DetajjL_;
  TBranch *DetajjL_branch;
  bool     DetajjL_isLoaded;
  float    DetajjL_up_;
  TBranch *DetajjL_up_branch;
  bool     DetajjL_up_isLoaded;
  float    DetajjL_dn_;
  TBranch *DetajjL_dn_branch;
  bool     DetajjL_dn_isLoaded;
  float    MllSS_;
  TBranch *MllSS_branch;
  bool     MllSS_isLoaded;
  float    MeeSS_;
  TBranch *MeeSS_branch;
  bool     MeeSS_isLoaded;
  float    Mll3L_;
  TBranch *Mll3L_branch;
  bool     Mll3L_isLoaded;
  float    Mee3L_;
  TBranch *Mee3L_branch;
  bool     Mee3L_isLoaded;
  float    Mll3L1_;
  TBranch *Mll3L1_branch;
  bool     Mll3L1_isLoaded;
  float    M3l_;
  TBranch *M3l_branch;
  bool     M3l_isLoaded;
  float    Pt3l_;
  TBranch *Pt3l_branch;
  bool     Pt3l_isLoaded;
  float    M01_;
  TBranch *M01_branch;
  bool     M01_isLoaded;
  float    M02_;
  TBranch *M02_branch;
  bool     M02_isLoaded;
  float    M12_;
  TBranch *M12_branch;
  bool     M12_isLoaded;
  int      isSFOS01_;
  TBranch *isSFOS01_branch;
  bool     isSFOS01_isLoaded;
  int      isSFOS02_;
  TBranch *isSFOS02_branch;
  bool     isSFOS02_isLoaded;
  int      isSFOS12_;
  TBranch *isSFOS12_branch;
  bool     isSFOS12_isLoaded;
  float    DPhi3lMET_;
  TBranch *DPhi3lMET_branch;
  bool     DPhi3lMET_isLoaded;
  float    DPhi3lMET_up_;
  TBranch *DPhi3lMET_up_branch;
  bool     DPhi3lMET_up_isLoaded;
  float    DPhi3lMET_dn_;
  TBranch *DPhi3lMET_dn_branch;
  bool     DPhi3lMET_dn_isLoaded;
  float    DPhi3lMET_gen_;
  TBranch *DPhi3lMET_gen_branch;
  bool     DPhi3lMET_gen_isLoaded;
  float    MTmax_;
  TBranch *MTmax_branch;
  bool     MTmax_isLoaded;
  float    MTmax_up_;
  TBranch *MTmax_up_branch;
  bool     MTmax_up_isLoaded;
  float    MTmax_dn_;
  TBranch *MTmax_dn_branch;
  bool     MTmax_dn_isLoaded;
  float    MTmax_gen_;
  TBranch *MTmax_gen_branch;
  bool     MTmax_gen_isLoaded;
  float    MTmin_;
  TBranch *MTmin_branch;
  bool     MTmin_isLoaded;
  float    MTmin_up_;
  TBranch *MTmin_up_branch;
  bool     MTmin_up_isLoaded;
  float    MTmin_dn_;
  TBranch *MTmin_dn_branch;
  bool     MTmin_dn_isLoaded;
  float    MTmin_gen_;
  TBranch *MTmin_gen_branch;
  bool     MTmin_gen_isLoaded;
  float    MT3rd_;
  TBranch *MT3rd_branch;
  bool     MT3rd_isLoaded;
  float    MT3rd_up_;
  TBranch *MT3rd_up_branch;
  bool     MT3rd_up_isLoaded;
  float    MT3rd_dn_;
  TBranch *MT3rd_dn_branch;
  bool     MT3rd_dn_isLoaded;
  float    MT3rd_gen_;
  TBranch *MT3rd_gen_branch;
  bool     MT3rd_gen_isLoaded;
  float    MTmax3L_;
  TBranch *MTmax3L_branch;
  bool     MTmax3L_isLoaded;
  float    MTmax3L_up_;
  TBranch *MTmax3L_up_branch;
  bool     MTmax3L_up_isLoaded;
  float    MTmax3L_dn_;
  TBranch *MTmax3L_dn_branch;
  bool     MTmax3L_dn_isLoaded;
  float    MTmax3L_gen_;
  TBranch *MTmax3L_gen_branch;
  bool     MTmax3L_gen_isLoaded;
  int      passSSee_;
  TBranch *passSSee_branch;
  bool     passSSee_isLoaded;
  int      passSSem_;
  TBranch *passSSem_branch;
  bool     passSSem_isLoaded;
  int      passSSmm_;
  TBranch *passSSmm_branch;
  bool     passSSmm_isLoaded;
  int      lep_idx0_SS_;
  TBranch *lep_idx0_SS_branch;
  bool     lep_idx0_SS_isLoaded;
  int      lep_idx1_SS_;
  TBranch *lep_idx1_SS_branch;
  bool     lep_idx1_SS_isLoaded;
  TString *bkgtype_;
  TBranch *bkgtype_branch;
  bool     bkgtype_isLoaded;
  int      vetophoton_;
  TBranch *vetophoton_branch;
  bool     vetophoton_isLoaded;
  float    purewgt_;
  TBranch *purewgt_branch;
  bool     purewgt_isLoaded;
  float    purewgt_up_;
  TBranch *purewgt_up_branch;
  bool     purewgt_up_isLoaded;
  float    purewgt_dn_;
  TBranch *purewgt_dn_branch;
  bool     purewgt_dn_isLoaded;
  float    ffwgt_;
  TBranch *ffwgt_branch;
  bool     ffwgt_isLoaded;
  float    ffwgt_up_;
  TBranch *ffwgt_up_branch;
  bool     ffwgt_up_isLoaded;
  float    ffwgt_dn_;
  TBranch *ffwgt_dn_branch;
  bool     ffwgt_dn_isLoaded;
  float    ffwgt_el_up_;
  TBranch *ffwgt_el_up_branch;
  bool     ffwgt_el_up_isLoaded;
  float    ffwgt_el_dn_;
  TBranch *ffwgt_el_dn_branch;
  bool     ffwgt_el_dn_isLoaded;
  float    ffwgt_mu_up_;
  TBranch *ffwgt_mu_up_branch;
  bool     ffwgt_mu_up_isLoaded;
  float    ffwgt_mu_dn_;
  TBranch *ffwgt_mu_dn_branch;
  bool     ffwgt_mu_dn_isLoaded;
  float    ffwgt_closure_up_;
  TBranch *ffwgt_closure_up_branch;
  bool     ffwgt_closure_up_isLoaded;
  float    ffwgt_closure_dn_;
  TBranch *ffwgt_closure_dn_branch;
  bool     ffwgt_closure_dn_isLoaded;
  float    ffwgt_closure_el_up_;
  TBranch *ffwgt_closure_el_up_branch;
  bool     ffwgt_closure_el_up_isLoaded;
  float    ffwgt_closure_el_dn_;
  TBranch *ffwgt_closure_el_dn_branch;
  bool     ffwgt_closure_el_dn_isLoaded;
  float    ffwgt_closure_mu_up_;
  TBranch *ffwgt_closure_mu_up_branch;
  bool     ffwgt_closure_mu_up_isLoaded;
  float    ffwgt_closure_mu_dn_;
  TBranch *ffwgt_closure_mu_dn_branch;
  bool     ffwgt_closure_mu_dn_isLoaded;
  float    ffwgt_full_up_;
  TBranch *ffwgt_full_up_branch;
  bool     ffwgt_full_up_isLoaded;
  float    ffwgt_full_dn_;
  TBranch *ffwgt_full_dn_branch;
  bool     ffwgt_full_dn_isLoaded;
  float    ffwgtqcd_;
  TBranch *ffwgtqcd_branch;
  bool     ffwgtqcd_isLoaded;
  float    ffwgtqcd_up_;
  TBranch *ffwgtqcd_up_branch;
  bool     ffwgtqcd_up_isLoaded;
  float    ffwgtqcd_dn_;
  TBranch *ffwgtqcd_dn_branch;
  bool     ffwgtqcd_dn_isLoaded;
  float    lepsf_;
  TBranch *lepsf_branch;
  bool     lepsf_isLoaded;
  float    lepsf_up_;
  TBranch *lepsf_up_branch;
  bool     lepsf_up_isLoaded;
  float    lepsf_dn_;
  TBranch *lepsf_dn_branch;
  bool     lepsf_dn_isLoaded;
  float    trigeff_;
  TBranch *trigeff_branch;
  bool     trigeff_isLoaded;
  float    trigeff_up_;
  TBranch *trigeff_up_branch;
  bool     trigeff_up_isLoaded;
  float    trigeff_dn_;
  TBranch *trigeff_dn_branch;
  bool     trigeff_dn_isLoaded;
  float    trigsf_;
  TBranch *trigsf_branch;
  bool     trigsf_isLoaded;
  float    trigsf_up_;
  TBranch *trigsf_up_branch;
  bool     trigsf_up_isLoaded;
  float    trigsf_dn_;
  TBranch *trigsf_dn_branch;
  bool     trigsf_dn_isLoaded;
  float    musmear_sf_;
  TBranch *musmear_sf_branch;
  bool     musmear_sf_isLoaded;
public: 
void Init(TTree *tree);
void GetEntry(unsigned int idx); 
void LoadAllBranches(); 
  const int &run();
  const int &lumi();
  const unsigned long long &evt();
  const int &isData();
  const float &evt_scale1fb();
  const float &xsec_br();
  const int &evt_passgoodrunlist();
  const TString &CMS4path();
  const int &CMS4index();
  const float &weight_fr_r1_f1();
  const float &weight_fr_r1_f2();
  const float &weight_fr_r1_f0p5();
  const float &weight_fr_r2_f1();
  const float &weight_fr_r2_f2();
  const float &weight_fr_r2_f0p5();
  const float &weight_fr_r0p5_f1();
  const float &weight_fr_r0p5_f2();
  const float &weight_fr_r0p5_f0p5();
  const float &weight_pdf_up();
  const float &weight_pdf_down();
  const float &weight_alphas_down();
  const float &weight_alphas_up();
  const float &weight_isr();
  const float &weight_isr_up();
  const float &weight_isr_down();
  const int &HLT_DoubleMu();
  const int &HLT_DoubleEl();
  const int &HLT_DoubleEl_DZ();
  const int &HLT_DoubleEl_DZ_2();
  const int &HLT_MuEG();
  const int &HLT_SingleEl8();
  const int &HLT_SingleEl17();
  const int &HLT_SingleIsoEl8();
  const int &HLT_SingleIsoEl17();
  const int &HLT_SingleIsoEl23();
  const int &HLT_SingleIsoMu8();
  const int &HLT_SingleIsoMu17();
  const int &HLT_PFMET140_PFMHT140_IDTight();
  const int &mc_HLT_DoubleMu();
  const int &mc_HLT_DoubleEl();
  const int &mc_HLT_DoubleEl_DZ();
  const int &mc_HLT_DoubleEl_DZ_2();
  const int &mc_HLT_MuEG();
  const int &mc_HLT_SingleEl8();
  const int &mc_HLT_SingleEl17();
  const int &mc_HLT_SingleIsoEl8();
  const int &mc_HLT_SingleIsoEl17();
  const int &mc_HLT_SingleIsoEl23();
  const int &mc_HLT_SingleIsoMu8();
  const int &mc_HLT_SingleIsoMu17();
  const int &mc_HLT_PFMET140_PFMHT140_IDTight();
  const int &pass_duplicate_ee_em_mm();
  const int &pass_duplicate_mm_em_ee();
  const int &is2016();
  const int &is2017();
  const int &HLT_MuEG_2016();
  const int &mc_HLT_MuEG_2016();
  const int &pass_duplicate_ee_em2016_mm();
  const int &pass_duplicate_mm_em2016_ee();
  const int &passTrigger();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
  const vector<float> &lep_pt();
  const vector<float> &lep_eta();
  const vector<float> &lep_phi();
  const vector<float> &lep_coneCorrPt();
  const vector<float> &lep_ip3d();
  const vector<float> &lep_ip3derr();
  const vector<int> &lep_isTriggerSafe_v1();
  const vector<int> &lep_lostHits();
  const vector<int> &lep_convVeto();
  const vector<int> &lep_motherIdSS();
  const vector<int> &lep_pass_VVV_cutbased_3l_fo();
  const vector<int> &lep_pass_VVV_cutbased_3l_tight();
  const vector<int> &lep_pass_VVV_cutbased_fo();
  const vector<int> &lep_pass_VVV_cutbased_tight();
  const vector<int> &lep_pass_VVV_cutbased_veto();
  const vector<int> &lep_pass_VVV_cutbased_fo_noiso();
  const vector<int> &lep_pass_VVV_cutbased_tight_noiso();
  const vector<int> &lep_pass_VVV_cutbased_veto_noiso();
  const vector<int> &lep_pass_POG_veto();
  const vector<int> &lep_pass_POG_loose();
  const vector<int> &lep_pass_POG_medium();
  const vector<int> &lep_pass_POG_tight();
  const vector<int> &lep_pdgId();
  const vector<float> &lep_dxy();
  const vector<float> &lep_dz();
  const vector<float> &lep_pterr();
  const vector<float> &lep_relIso04DB();
  const vector<float> &lep_relIso03EA();
  const vector<float> &lep_relIso03EALep();
  const vector<float> &lep_relIso03EAv2();
  const vector<float> &lep_relIso04EAv2();
  const vector<float> &lep_relIso03EAv2Lep();
  const vector<int> &lep_tightCharge();
  const vector<float> &lep_trk_pt();
  const vector<int> &lep_charge();
  const vector<float> &lep_etaSC();
  const vector<float> &lep_MVA();
  const vector<int> &lep_isMediumPOG();
  const vector<int> &lep_isTightPOG();
  const vector<int> &lep_isFromW();
  const vector<int> &lep_isFromZ();
  const vector<int> &lep_isFromB();
  const vector<int> &lep_isFromC();
  const vector<int> &lep_isFromL();
  const vector<int> &lep_isFromLF();
  const vector<int> &lep_genPart_index();
  const vector<float> &lep_r9();
  const vector<int> &lep_nlayers();
  const float &el_pt();
  const float &el_eta();
  const float &el_phi();
  const float &el_relIso03EA();
  const float &el_relIso03EALep();
  const float &el_ip3d();
  const float &mu_pt();
  const float &mu_eta();
  const float &mu_phi();
  const float &mu_relIso04DB();
  const float &mu_relIso03EA();
  const float &mu_relIso03EALep();
  const float &mu_ip3d();
  const float &lbnt_pt();
  const float &lbnt_coneCorrPt();
  const float &lbnt_abseta();
  const float &lbnt_pdgId();
  const float &lbnt_el_pt();
  const float &lbnt_el_coneCorrPt();
  const float &lbnt_el_abseta();
  const float &lbnt_mu_pt();
  const float &lbnt_mu_coneCorrPt();
  const float &lbnt_mu_abseta();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
  const vector<float> &jets_csv();
  const vector<float> &jets_up_csv();
  const vector<float> &jets_dn_csv();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak8jets_p4();
  const vector<float> &ak8jets_softdropMass();
  const vector<float> &ak8jets_prunedMass();
  const vector<float> &ak8jets_trimmedMass();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_nJettinessTau1();
  const vector<float> &ak8jets_nJettinessTau2();
  const vector<float> &ak8jets_softdropPuppiSubjet1();
  const vector<float> &ak8jets_softdropPuppiSubjet2();
  const vector<float> &ak8jets_puppi_softdropMass();
  const vector<float> &ak8jets_puppi_nJettinessTau1();
  const vector<float> &ak8jets_puppi_nJettinessTau2();
  const vector<float> &ak8jets_puppi_eta();
  const vector<float> &ak8jets_puppi_phi();
  const vector<float> &ak8jets_puppi_pt();
  const vector<float> &ak8jets_puppi_mass();
  const float &met_pt();
  const float &met_phi();
  const float &met_up_pt();
  const float &met_up_phi();
  const float &met_dn_pt();
  const float &met_dn_phi();
  const float &met_gen_pt();
  const float &met_gen_phi();
  const int &firstgoodvertex();
  const int &nTrueInt();
  const int &nVert();
  const int &nisoTrack_mt2_cleaned_VVV_cutbased_veto();
  const float &weight_btagsf();
  const float &weight_btagsf_heavy_DN();
  const float &weight_btagsf_heavy_UP();
  const float &weight_btagsf_light_DN();
  const float &weight_btagsf_light_UP();
  const float &gen_ht();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
  const vector<int> &genPart_motherId();
  const vector<int> &genPart_pdgId();
  const vector<int> &genPart_charge();
  const vector<int> &genPart_status();
  const int &ngenLep();
  const int &ngenLepFromTau();
  const int &Flag_AllEventFilters();
  const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
  const int &Flag_HBHEIsoNoiseFilter();
  const int &Flag_HBHENoiseFilter();
  const int &Flag_badChargedCandidateFilter();
  const int &Flag_badMuonFilter();
  const int &Flag_badMuonFilterv2();
  const int &Flag_badChargedCandidateFilterv2();
  const int &Flag_eeBadScFilter();
  const int &Flag_ecalBadCalibFilter();
  const int &Flag_globalTightHalo2016();
  const int &Flag_goodVertices();
  const int &Flag_ecalLaserCorrFilter();
  const int &Flag_hcalLaserEventFilter();
  const int &Flag_trackingFailureFilter();
  const int &Flag_CSCTightHaloFilter();
  const int &Flag_CSCTightHalo2015Filter();
  const int &Flag_badMuons();
  const int &Flag_duplicateMuons();
  const int &Flag_noBadMuons();
  const int &fastsimfilt();
  const int &nVlep();
  const int &nTlep();
  const int &nTlepSS();
  const int &nLlep();
  const int &nSFOS();
  const int &nSFOSinZ();
  const int &nj();
  const int &nj_up();
  const int &nj_dn();
  const int &nj30();
  const int &nj30_up();
  const int &nj30_dn();
  const int &nb();
  const int &nb_up();
  const int &nb_dn();
  const float &Mjj();
  const float &Mjj_up();
  const float &Mjj_dn();
  const float &DRjj();
  const float &DRjj_up();
  const float &DRjj_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_dn();
  const float &MjjDR1();
  const float &MjjDR1_up();
  const float &MjjDR1_dn();
  const float &DRjjDR1();
  const float &DRjjDR1_up();
  const float &DRjjDR1_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1_dn();
  const float &MjjVBF();
  const float &MjjVBF_up();
  const float &MjjVBF_dn();
  const float &DetajjVBF();
  const float &DetajjVBF_up();
  const float &DetajjVBF_dn();
  const float &MjjL();
  const float &MjjL_up();
  const float &MjjL_dn();
  const float &DetajjL();
  const float &DetajjL_up();
  const float &DetajjL_dn();
  const float &MllSS();
  const float &MeeSS();
  const float &Mll3L();
  const float &Mee3L();
  const float &Mll3L1();
  const float &M3l();
  const float &Pt3l();
  const float &M01();
  const float &M02();
  const float &M12();
  const int &isSFOS01();
  const int &isSFOS02();
  const int &isSFOS12();
  const float &DPhi3lMET();
  const float &DPhi3lMET_up();
  const float &DPhi3lMET_dn();
  const float &DPhi3lMET_gen();
  const float &MTmax();
  const float &MTmax_up();
  const float &MTmax_dn();
  const float &MTmax_gen();
  const float &MTmin();
  const float &MTmin_up();
  const float &MTmin_dn();
  const float &MTmin_gen();
  const float &MT3rd();
  const float &MT3rd_up();
  const float &MT3rd_dn();
  const float &MT3rd_gen();
  const float &MTmax3L();
  const float &MTmax3L_up();
  const float &MTmax3L_dn();
  const float &MTmax3L_gen();
  const int &passSSee();
  const int &passSSem();
  const int &passSSmm();
  const int &lep_idx0_SS();
  const int &lep_idx1_SS();
  const TString &bkgtype();
  const int &vetophoton();
  const float &purewgt();
  const float &purewgt_up();
  const float &purewgt_dn();
  const float &ffwgt();
  const float &ffwgt_up();
  const float &ffwgt_dn();
  const float &ffwgt_el_up();
  const float &ffwgt_el_dn();
  const float &ffwgt_mu_up();
  const float &ffwgt_mu_dn();
  const float &ffwgt_closure_up();
  const float &ffwgt_closure_dn();
  const float &ffwgt_closure_el_up();
  const float &ffwgt_closure_el_dn();
  const float &ffwgt_closure_mu_up();
  const float &ffwgt_closure_mu_dn();
  const float &ffwgt_full_up();
  const float &ffwgt_full_dn();
  const float &ffwgtqcd();
  const float &ffwgtqcd_up();
  const float &ffwgtqcd_dn();
  const float &lepsf();
  const float &lepsf_up();
  const float &lepsf_dn();
  const float &trigeff();
  const float &trigeff_up();
  const float &trigeff_dn();
  const float &trigsf();
  const float &trigsf_up();
  const float &trigsf_dn();
  const float &musmear_sf();

  static void progress(int nEventsTotal, int nEventsChain);
};

#ifndef __CINT__
extern frtree fr;
#endif

namespace tas {
  const int &run();
  const int &lumi();
  const unsigned long long &evt();
  const int &isData();
  const float &evt_scale1fb();
  const float &xsec_br();
  const int &evt_passgoodrunlist();
  const TString &CMS4path();
  const int &CMS4index();
  const float &weight_fr_r1_f1();
  const float &weight_fr_r1_f2();
  const float &weight_fr_r1_f0p5();
  const float &weight_fr_r2_f1();
  const float &weight_fr_r2_f2();
  const float &weight_fr_r2_f0p5();
  const float &weight_fr_r0p5_f1();
  const float &weight_fr_r0p5_f2();
  const float &weight_fr_r0p5_f0p5();
  const float &weight_pdf_up();
  const float &weight_pdf_down();
  const float &weight_alphas_down();
  const float &weight_alphas_up();
  const float &weight_isr();
  const float &weight_isr_up();
  const float &weight_isr_down();
  const int &HLT_DoubleMu();
  const int &HLT_DoubleEl();
  const int &HLT_DoubleEl_DZ();
  const int &HLT_DoubleEl_DZ_2();
  const int &HLT_MuEG();
  const int &HLT_SingleEl8();
  const int &HLT_SingleEl17();
  const int &HLT_SingleIsoEl8();
  const int &HLT_SingleIsoEl17();
  const int &HLT_SingleIsoEl23();
  const int &HLT_SingleIsoMu8();
  const int &HLT_SingleIsoMu17();
  const int &HLT_PFMET140_PFMHT140_IDTight();
  const int &mc_HLT_DoubleMu();
  const int &mc_HLT_DoubleEl();
  const int &mc_HLT_DoubleEl_DZ();
  const int &mc_HLT_DoubleEl_DZ_2();
  const int &mc_HLT_MuEG();
  const int &mc_HLT_SingleEl8();
  const int &mc_HLT_SingleEl17();
  const int &mc_HLT_SingleIsoEl8();
  const int &mc_HLT_SingleIsoEl17();
  const int &mc_HLT_SingleIsoEl23();
  const int &mc_HLT_SingleIsoMu8();
  const int &mc_HLT_SingleIsoMu17();
  const int &mc_HLT_PFMET140_PFMHT140_IDTight();
  const int &pass_duplicate_ee_em_mm();
  const int &pass_duplicate_mm_em_ee();
  const int &is2016();
  const int &is2017();
  const int &HLT_MuEG_2016();
  const int &mc_HLT_MuEG_2016();
  const int &pass_duplicate_ee_em2016_mm();
  const int &pass_duplicate_mm_em2016_ee();
  const int &passTrigger();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
  const vector<float> &lep_pt();
  const vector<float> &lep_eta();
  const vector<float> &lep_phi();
  const vector<float> &lep_coneCorrPt();
  const vector<float> &lep_ip3d();
  const vector<float> &lep_ip3derr();
  const vector<int> &lep_isTriggerSafe_v1();
  const vector<int> &lep_lostHits();
  const vector<int> &lep_convVeto();
  const vector<int> &lep_motherIdSS();
  const vector<int> &lep_pass_VVV_cutbased_3l_fo();
  const vector<int> &lep_pass_VVV_cutbased_3l_tight();
  const vector<int> &lep_pass_VVV_cutbased_fo();
  const vector<int> &lep_pass_VVV_cutbased_tight();
  const vector<int> &lep_pass_VVV_cutbased_veto();
  const vector<int> &lep_pass_VVV_cutbased_fo_noiso();
  const vector<int> &lep_pass_VVV_cutbased_tight_noiso();
  const vector<int> &lep_pass_VVV_cutbased_veto_noiso();
  const vector<int> &lep_pass_POG_veto();
  const vector<int> &lep_pass_POG_loose();
  const vector<int> &lep_pass_POG_medium();
  const vector<int> &lep_pass_POG_tight();
  const vector<int> &lep_pdgId();
  const vector<float> &lep_dxy();
  const vector<float> &lep_dz();
  const vector<float> &lep_pterr();
  const vector<float> &lep_relIso04DB();
  const vector<float> &lep_relIso03EA();
  const vector<float> &lep_relIso03EALep();
  const vector<float> &lep_relIso03EAv2();
  const vector<float> &lep_relIso04EAv2();
  const vector<float> &lep_relIso03EAv2Lep();
  const vector<int> &lep_tightCharge();
  const vector<float> &lep_trk_pt();
  const vector<int> &lep_charge();
  const vector<float> &lep_etaSC();
  const vector<float> &lep_MVA();
  const vector<int> &lep_isMediumPOG();
  const vector<int> &lep_isTightPOG();
  const vector<int> &lep_isFromW();
  const vector<int> &lep_isFromZ();
  const vector<int> &lep_isFromB();
  const vector<int> &lep_isFromC();
  const vector<int> &lep_isFromL();
  const vector<int> &lep_isFromLF();
  const vector<int> &lep_genPart_index();
  const vector<float> &lep_r9();
  const vector<int> &lep_nlayers();
  const float &el_pt();
  const float &el_eta();
  const float &el_phi();
  const float &el_relIso03EA();
  const float &el_relIso03EALep();
  const float &el_ip3d();
  const float &mu_pt();
  const float &mu_eta();
  const float &mu_phi();
  const float &mu_relIso04DB();
  const float &mu_relIso03EA();
  const float &mu_relIso03EALep();
  const float &mu_ip3d();
  const float &lbnt_pt();
  const float &lbnt_coneCorrPt();
  const float &lbnt_abseta();
  const float &lbnt_pdgId();
  const float &lbnt_el_pt();
  const float &lbnt_el_coneCorrPt();
  const float &lbnt_el_abseta();
  const float &lbnt_mu_pt();
  const float &lbnt_mu_coneCorrPt();
  const float &lbnt_mu_abseta();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
  const vector<float> &jets_csv();
  const vector<float> &jets_up_csv();
  const vector<float> &jets_dn_csv();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak8jets_p4();
  const vector<float> &ak8jets_softdropMass();
  const vector<float> &ak8jets_prunedMass();
  const vector<float> &ak8jets_trimmedMass();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_nJettinessTau1();
  const vector<float> &ak8jets_nJettinessTau2();
  const vector<float> &ak8jets_softdropPuppiSubjet1();
  const vector<float> &ak8jets_softdropPuppiSubjet2();
  const vector<float> &ak8jets_puppi_softdropMass();
  const vector<float> &ak8jets_puppi_nJettinessTau1();
  const vector<float> &ak8jets_puppi_nJettinessTau2();
  const vector<float> &ak8jets_puppi_eta();
  const vector<float> &ak8jets_puppi_phi();
  const vector<float> &ak8jets_puppi_pt();
  const vector<float> &ak8jets_puppi_mass();
  const float &met_pt();
  const float &met_phi();
  const float &met_up_pt();
  const float &met_up_phi();
  const float &met_dn_pt();
  const float &met_dn_phi();
  const float &met_gen_pt();
  const float &met_gen_phi();
  const int &firstgoodvertex();
  const int &nTrueInt();
  const int &nVert();
  const int &nisoTrack_mt2_cleaned_VVV_cutbased_veto();
  const float &weight_btagsf();
  const float &weight_btagsf_heavy_DN();
  const float &weight_btagsf_heavy_UP();
  const float &weight_btagsf_light_DN();
  const float &weight_btagsf_light_UP();
  const float &gen_ht();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
  const vector<int> &genPart_motherId();
  const vector<int> &genPart_pdgId();
  const vector<int> &genPart_charge();
  const vector<int> &genPart_status();
  const int &ngenLep();
  const int &ngenLepFromTau();
  const int &Flag_AllEventFilters();
  const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
  const int &Flag_HBHEIsoNoiseFilter();
  const int &Flag_HBHENoiseFilter();
  const int &Flag_badChargedCandidateFilter();
  const int &Flag_badMuonFilter();
  const int &Flag_badMuonFilterv2();
  const int &Flag_badChargedCandidateFilterv2();
  const int &Flag_eeBadScFilter();
  const int &Flag_ecalBadCalibFilter();
  const int &Flag_globalTightHalo2016();
  const int &Flag_goodVertices();
  const int &Flag_ecalLaserCorrFilter();
  const int &Flag_hcalLaserEventFilter();
  const int &Flag_trackingFailureFilter();
  const int &Flag_CSCTightHaloFilter();
  const int &Flag_CSCTightHalo2015Filter();
  const int &Flag_badMuons();
  const int &Flag_duplicateMuons();
  const int &Flag_noBadMuons();
  const int &fastsimfilt();
  const int &nVlep();
  const int &nTlep();
  const int &nTlepSS();
  const int &nLlep();
  const int &nSFOS();
  const int &nSFOSinZ();
  const int &nj();
  const int &nj_up();
  const int &nj_dn();
  const int &nj30();
  const int &nj30_up();
  const int &nj30_dn();
  const int &nb();
  const int &nb_up();
  const int &nb_dn();
  const float &Mjj();
  const float &Mjj_up();
  const float &Mjj_dn();
  const float &DRjj();
  const float &DRjj_up();
  const float &DRjj_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_dn();
  const float &MjjDR1();
  const float &MjjDR1_up();
  const float &MjjDR1_dn();
  const float &DRjjDR1();
  const float &DRjjDR1_up();
  const float &DRjjDR1_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet0_wtag_p4_DR1_dn();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1_up();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet1_wtag_p4_DR1_dn();
  const float &MjjVBF();
  const float &MjjVBF_up();
  const float &MjjVBF_dn();
  const float &DetajjVBF();
  const float &DetajjVBF_up();
  const float &DetajjVBF_dn();
  const float &MjjL();
  const float &MjjL_up();
  const float &MjjL_dn();
  const float &DetajjL();
  const float &DetajjL_up();
  const float &DetajjL_dn();
  const float &MllSS();
  const float &MeeSS();
  const float &Mll3L();
  const float &Mee3L();
  const float &Mll3L1();
  const float &M3l();
  const float &Pt3l();
  const float &M01();
  const float &M02();
  const float &M12();
  const int &isSFOS01();
  const int &isSFOS02();
  const int &isSFOS12();
  const float &DPhi3lMET();
  const float &DPhi3lMET_up();
  const float &DPhi3lMET_dn();
  const float &DPhi3lMET_gen();
  const float &MTmax();
  const float &MTmax_up();
  const float &MTmax_dn();
  const float &MTmax_gen();
  const float &MTmin();
  const float &MTmin_up();
  const float &MTmin_dn();
  const float &MTmin_gen();
  const float &MT3rd();
  const float &MT3rd_up();
  const float &MT3rd_dn();
  const float &MT3rd_gen();
  const float &MTmax3L();
  const float &MTmax3L_up();
  const float &MTmax3L_dn();
  const float &MTmax3L_gen();
  const int &passSSee();
  const int &passSSem();
  const int &passSSmm();
  const int &lep_idx0_SS();
  const int &lep_idx1_SS();
  const TString &bkgtype();
  const int &vetophoton();
  const float &purewgt();
  const float &purewgt_up();
  const float &purewgt_dn();
  const float &ffwgt();
  const float &ffwgt_up();
  const float &ffwgt_dn();
  const float &ffwgt_el_up();
  const float &ffwgt_el_dn();
  const float &ffwgt_mu_up();
  const float &ffwgt_mu_dn();
  const float &ffwgt_closure_up();
  const float &ffwgt_closure_dn();
  const float &ffwgt_closure_el_up();
  const float &ffwgt_closure_el_dn();
  const float &ffwgt_closure_mu_up();
  const float &ffwgt_closure_mu_dn();
  const float &ffwgt_full_up();
  const float &ffwgt_full_dn();
  const float &ffwgtqcd();
  const float &ffwgtqcd_up();
  const float &ffwgtqcd_dn();
  const float &lepsf();
  const float &lepsf_up();
  const float &lepsf_dn();
  const float &trigeff();
  const float &trigeff_up();
  const float &trigeff_dn();
  const float &trigsf();
  const float &trigsf_up();
  const float &trigsf_dn();
  const float &musmear_sf();
}
#include "rooutil/rooutil.h"
#endif
